tokenizer_model_path: "/home/coder/generative-ai-research-babylm/models/tokenizer/train_10M/GPT2_WML"
model_path: "/home/coder/generative-ai-research-babylm/models/WML/n_peer_4"
device: "cuda:0"
model_args_path: "/home/coder/generative-ai-research-babylm/conf/blm-main.yaml"
max_length: 64
batch_size: 128
MRL_enabled: True
MRL_dim_idx: 0 
temperature: 0.1
top_k: 20
evaluate_ensemble: True
